name: Download Dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Zip node_modules
        run: zip -r node_modules.zip node_modules

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules.zip
